name: Generate and Upload Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12.3'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Timezone setup 
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Canada/Eastern"

    - name: Generate plot
      run: |
        python src/durations.py
  
    - name: Commit and push plot image
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        if [ ! -d "output/images" ]; then mkdir -p output/images; fi
        
        # Move and commit all PNG files
        for img in $(ls *.png); do
          mv "$img" output/images/
          git add output/images/"$img"
        done
        
       
        git diff --quiet && git diff --staged --quiet || (
          git commit -m 'Automated push of images' &&
          git push
        )